# === SimpleItemSign Configuration === #
# You don't need to modify anything, the plugin will work perfectly

# The size of the "sign-inventory"
# Options are: 9, 18, 27, 36, 45, 54
inventorySize: 9

# If this is true, only players with the "simpleitemsigns.use" permission will be able to open the ItemSigns
needUsePermission: false

# If this is true, items which aren't from the ItemSign will be dropped on the ground when the player closes the inventory
dontTrash: true