###########################################################
# - SimpleItemSigns Configuration - Plugin by: Trigary - #
###########################################################
# All commands are explained when you enter one incorrectly and they all require the "simpleitemsigns.admin" permission
# Command aliases: /simpleitemsigns | /sis



# If this is true, only players with the "simpleitemsigns.use" permission will be able to open ItemSigns
needUsePermission: false

# How many rows should be in a sign-inventory?
# Options: 1, 2, 3, 4, 5, 6
rows: 3

# If this is true, items which aren't from the ItemSign will be dropped on the ground when the player closes the ItemSign
dontTrash: true